heat_template_version: 2013-05-23

description: Provisions the infrastructure for an OpenShift Environment

parameters:
  external_network:
    type: string
    label: External Network
    description: >
      The external network that provides floating IP addresses for the nodes
    default: public
  image:
    type: string
    description: Image to use
    default: rhel-guest-image-7.5-update-3
  flavor:
    type: string
    description: Flavor to use
    default: m1.medium
  key:
    type: string
    description: Key to use
    default: root

resources:
  master-sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: master-sg
      rules:
      - protocol: icmp
      - direction: ingress
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - direction: ingress
        protocol: tcp
        port_range_min: 4001
        port_range_max: 4001
      - direction: ingress
        protocol: tcp
        port_range_min: 8443
        port_range_max: 8443
      - direction: ingress
        protocol: tcp
        port_range_min: 53
        port_range_max: 53
      - direction: ingress
        protocol: udp
        port_range_min: 53
        port_range_max: 53
      - direction: ingress
        protocol: udp
        port_range_min: 4789
        port_range_max: 4789
      - direction: ingress
        protocol: tcp
        port_range_min: 8053
        port_range_max: 8053
      - direction: ingress
        protocol: udp
        port_range_min: 8053
        port_range_max: 8053
      - direction: ingress
        protocol: tcp
        port_range_min: 10250
        port_range_max: 10250
      - direction: ingress
        protocol: tcp
        port_range_min: 24224
        port_range_max: 24224
      - direction: ingress
        protocol: udp
        port_range_min: 24224
        port_range_max: 24224
      - direction: ingress
        protocol: tcp
        port_range_min: 2379
        port_range_max: 2379
      - direction: ingress
        protocol: tcp
        port_range_min: 2380
        port_range_max: 2380
        remote_mode: remote_group_id
  
  infra-node-sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: infra-node-sg
      rules:
      - protocol: icmp
      - direction: ingress
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - direction: ingress
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
      - direction: ingress
        protocol: tcp
        port_range_min: 443
        port_range_max: 443
      - direction: ingress
        protocol: tcp
        port_range_min: 10250
        port_range_max: 10250
      - direction: ingress
        protocol: udp
        port_range_min: 4789
        port_range_max: 4789
      - direction: ingress
        protocol: tcp
        port_range_min: 5000
        port_range_max: 5000
      - protocol: 112
  
  app-node-sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: app-node-sg
      rules:
      - protocol: icmp
      - direction: ingress
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - direction: ingress
        protocol: tcp
        port_range_min: 10250
        port_range_max: 10250
      - direction: ingress
        protocol: udp
        port_range_min: 4789
        port_range_max: 4789
  
  masters:
    type: OS::Heat::ResourceGroup
    properties:
      count: 1
      resource_def:
        type: ocp-master.yaml
        properties:
          hostname: master-%index%
          image: { get_param: image }
          flavor: { get_param: flavor }
          key: { get_param: key }

  infra:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: ocp-infra.yaml
        properties:
          hostname: infra-node-%index%
          image: { get_param: image }
          flavor: { get_param: flavor }
          key: { get_param: key }

  app:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: ocp-app.yaml
        properties:
          hostname: app-node-%index%
          image: { get_param: image }
          flavor: { get_param: flavor }
          key: { get_param: key }

